[package]
name = "source-map"
version = "0.8.0"
authors = ["kaleidawave <kaleidawave@gmail.com>"]
edition = "2018"
description = "Utilities for building source maps (v3) for a compiler"
license = "MIT"
keywords = ["source-map"]
categories = ["web-programming"]
repository = "https://github.com/kaleidawave/source-map"

[dependencies]
lazy_static = "1.4.0"
lsp-types = { version = "0.91.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
base64 = { version = "0.13.0", optional = true }

[features]
lsp-types-morphisms = ["lsp-types"]
span-serialize = ["serde"]
u32-span = []
inline-source-map = ["base64"]
