name: Crates Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "major/minor/patch or semver"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install cargo edit (fork)
        run: cargo install --git https://github.com/kaleidawave/cargo-edit --branch new-set-version-options cargo-edit
      - name: Set version semver
        run: echo "::set-output name=newVersion::$( cargo set-version --output-new-version --panic-if-equal --raw ${{ github.event.inputs.version }} )"
      - name: Publish on crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --allow-dirty
      - name: Push updated Cargo.toml
        run: |
          git tag "v${{ steps.versioner.outputs.newVersion }}"
          git add .
          git commit -m "Release: ${{ steps.versioner.outputs.newVersion }}"
          git push --tags origin main
